#pragma once

#define STRIKE_KEY_NONE							0
#define STRIKE_KEY_LEFT								1
#define STRIKE_KEY_RIGHT							2
#define STRIKE_KEY_UP									3
#define STRIKE_KEY_DOWN							4

#define STRIKE_KEY_SPACE							5

#define STRIKE_KEY_0									6
#define STRIKE_KEY_1									7
#define STRIKE_KEY_2									8
#define STRIKE_KEY_3									9
#define STRIKE_KEY_4									10
#define STRIKE_KEY_5									11
#define STRIKE_KEY_6									12
#define STRIKE_KEY_7									13
#define STRIKE_KEY_8									14
#define STRIKE_KEY_9									15

#define STRIKE_KEY_EXCLAMATION				16
#define STRIKE_KEY_COMMA							17

#define STRIKE_KEY_ESCAPE							18 
#define STRIKE_KEY_F1									19
#define STRIKE_KEY_F2									20 
#define STRIKE_KEY_F3									21 
#define STRIKE_KEY_F4									22
#define STRIKE_KEY_F5									23 
#define STRIKE_KEY_F6									24 
#define STRIKE_KEY_F7									25 
#define STRIKE_KEY_F8									26 
#define STRIKE_KEY_F9									27 
#define STRIKE_KEY_F10								28
#define STRIKE_KEY_F11									29
#define STRIKE_KEY_F12								30
#define STRIKE_KEY_INSERT							31
#define STRIKE_KEY_DELETE							32
#define STRIKE_KEY_TAB								33
#define STRIKE_KEY_ICOMMA						34
#define STRIKE_KEY_LEFT_SHIFT					35
#define STRIKE_KEY_RIGHT_SHIFT				36
#define STRIKE_KEY_CAPS_LOCK					37
#define STRIKE_KEY_LEFT_CONTROL				38
#define STRIKE_KEY_RIGHT_CONTROL			39
#define STRIKE_KEY_LEFT_WINDOWS			40
#define STRIKE_KEY_RIGHT_WINDOWS		41
#define STRIKE_KEY_LEFT_ALT						42
#define STRIKE_KEY_RIGHT_ALT					43
#define STRIKE_KEY_FN           						44
#define STRIKE_KEY_DQUOTE	 					45
#define STRIKE_KEY_POUND							46
#define STRIKE_KEY_DOLLAR							47
#define STRIKE_KEY_PERCENTAGE					48
#define STRIKE_KEY_CARET							49
#define STRIKE_KEY_AMPERSAND					50
#define STRIKE_KEY_DASH							51
#define STRIKE_KEY_UNDERLINE					52
#define STRIKE_KEY_LBRACKET						53
#define STRIKE_KEY_RBRAKCET						54
#define STRIKE_KEY_ANGULAR_LBRACKET		55
#define STRIKE_KEY_ANGULAR_RBRACKET	56
#define STRIKE_KEY_BACKSPACE					57
#define STRIKE_KEY_SEMICOLON					58
#define STRIKE_KEY_SLASH							59
#define STRIKE_KEY_FULLSTOP						60
#define STRIKE_KEY_APOSTROPHE				61
#define STRIKE_KEY_ENTER							62

#define STRIKE_KEY_A									65
#define STRIKE_KEY_B									66
#define STRIKE_KEY_C									67
#define STRIKE_KEY_D									68
#define STRIKE_KEY_E									69
#define STRIKE_KEY_F									70
#define STRIKE_KEY_G									71
#define STRIKE_KEY_H									72
#define STRIKE_KEY_I									73
#define STRIKE_KEY_J									74
#define STRIKE_KEY_K									75
#define STRIKE_KEY_L									76
#define STRIKE_KEY_M									77
#define STRIKE_KEY_N									78
#define STRIKE_KEY_O									79
#define STRIKE_KEY_P									80
#define STRIKE_KEY_Q									81
#define STRIKE_KEY_R									82
#define STRIKE_KEY_S									83
#define STRIKE_KEY_T									84
#define STRIKE_KEY_U									85
#define STRIKE_KEY_V									86
#define STRIKE_KEY_W									87
#define STRIKE_KEY_X									88
#define STRIKE_KEY_Y									89
#define STRIKE_KEY_Z									90


#define STRIKE_TOTAL_KEYS							91