#pragma once

#define STRIKE_MOUSE_BUTTON_NONE		0
#define STRIKE_MOUSE_BUTTON_LEFT		1
#define STRIKE_MOUSE_BUTTON_RIGHT		2
#define STRIKE_MOUSE_BUTTON_MIDDLE	3

#define STRIKE_TOTAL_MOUSE_BUTTONS	4